require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # ── Host Authorization (dev only) ──
  # Allow all public-tunnel providers we use for Shopify webhooks + testing.
  # Add an explicit host via WEBHOOK_HOST=xxx.example.com if you use something else.
  config.hosts << /.*\.ngrok-free\.dev\z/
  config.hosts << /.*\.ngrok-free\.app\z/
  config.hosts << /.*\.ngrok\.io\z/
  config.hosts << /.*\.ngrok\.app\z/
  config.hosts << /.*\.trycloudflare\.com\z/
  config.hosts << /.*\.loca\.lt\z/
  if ENV["WEBHOOK_HOST"].present?
    config.hosts << ENV["WEBHOOK_HOST"]
  end
  if ENV["WEBHOOK_BASE_URL"].present?
    begin
      config.hosts << URI.parse(ENV["WEBHOOK_BASE_URL"]).host
    rescue URI::InvalidURIError
      # ignore
    end
  end

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
